apiVersion: v1
kind: Pod
metadata:
  name: stack-api-persona-1
  namespace: default
  annotations:
    sample: 800-555-1212
  labels:
    app: api-persona-1
    version: v1
spec:
  
  containers:
   - name: api-persona 
     image: jbarrera99/api-persona-v1:latest
     imagePullPolicy: IfNotPresent
     ports:
        - containerPort: 8080
     env:
        - name: host
          value: localhost
        - name: port
          value: "3306"
   - name: bd   
     image: jbarrera99/bd-mysql:latest
     ports:
        - containerPort: 3306
  restartPolicy: OnFailure #valores posibles -> Always, OnFailuer, Never
