apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: ClusterIP
  selector:
    app: api-persona-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # puertos que usan los pods

# kubectl exec -it pod-name -- sh
# apk add --no-cache curl
# curl cluster-ip:80
# -> cluster-ip es el valor de clusterIP en tu servicio.